#!/usr/bin/env bash
# Generates asterisk/etc/pjsip/pjsip_auth.conf with random passwords for the
# test extensions (1001-1003), from pjsip_auth.conf.example. The output file
# is gitignored — never commit it.
#
# Usage: ./generate_sip_secrets.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PJSIP_DIR="$SCRIPT_DIR/../etc/pjsip"
OUT_FILE="$PJSIP_DIR/pjsip_auth.conf"

if [ -f "$OUT_FILE" ]; then
    echo "Refusing to overwrite existing $OUT_FILE (delete it first if you want new passwords)." >&2
    exit 1
fi

random_password() {
    openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | head -c 24
}

{
    echo "; Generated by generate_sip_secrets.sh — DO NOT COMMIT."
    echo
    for ext in 1001 1002 1003; do
        pass="$(random_password)"
        echo "[$ext]"
        echo "type=auth"
        echo "auth_type=userpass"
        echo "username=$ext"
        echo "password=$pass"
        echo
    done
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
echo "Extension passwords (record these somewhere safe — they are not printed again):"
grep -A3 '^\[' "$OUT_FILE" | grep -E '^\[|password='
